Implement metadata views
xG-Studios/xGStudio-Flow-Smart-Contract pull request #2
Opened 2022-09-08 20:52 UTC by maggo

This adds metadata views as required by the NFT catalogue.

Supported views:

```
MetadataViews.Display
MetadataViews.Editions
MetadataViews.NFTCollectionDisplay
MetadataViews.ExternalURL
MetadataViews.NFTCollectionData
MetadataViews.Royalties
MetadataViews.Serial
```

## Todo

* [ ] Mapping and fallback for legacy template thumbnails
* [ ] Implement dynamic editions functionality (Editions based nft type)
* [ ] Set website URL fallback
* [ ] Add functionality to generate dynamic socials list
* [ ] Implement royalties

2022-09-20 13:36 UTC, yellowBirdy commented on contracts/XGStudio.cdc
> +                        name: brand.brandName == "xGrunning" ? "xGMove" : brand.brandName,
I've updated the brand metadata with name field, we should replace the line with 
```suggestion
                        name: brand.brandName == brand.data["name"],
```

2022-09-20 13:36 UTC, yellowBirdy commented on contracts/XGStudio.cdc
> +                        externalURL: MetadataViews.ExternalURL(brand.data["websiteUrl"] ?? "https://xgrunning.io"), // @TODO: Update fallback
It really should never happen as we need this for the the external url in the Display view but let's have

```suggestion
                        externalURL: MetadataViews.ExternalURL(brand.data["websiteUrl"] ?? "https://xgstudios.io"), // @TODO: Update fallback
```

2022-09-20 13:36 UTC, yellowBirdy commented on contracts/XGStudio.cdc
> +                            // @TODO: Implement dynamic socials list
would it make sense to add `social` field on brand.data containing a string with comma separated list of available socials which then would be parsed into an array and iterated over like:
`
brand.data = {
              ....,
             "socials": "twitter,instagram,discord",
             "twitter": "url1",
             "instagram": "url2",
              "discord": "url3"
              ...,
  }
  
  // here the magic happens ;) meaning iI don't know if possible
  let availableSocials = split(brand.data["socials"], ",")
  for social in availableSocials {
       socials[social] = brand.data[social]
  }

`

2022-09-20 13:36 UTC, yellowBirdy commented on contracts/XGStudio.cdc
> +                    return MetadataViews.ExternalURL((brand.data["websiteUrl"] ?? "https://xgrunning.io").concat("/rewards/").concat(self.id.toString())) // @TODO: Update fallback
It won't work at first, but will implement that later on 

```suggestion
                    return MetadataViews.ExternalURL((brand.data["websiteUrl"] ?? "https://xgstudios.io").concat("/rewards/").concat(self.id.toString())) // @TODO: Update fallback
```

2022-09-20 13:48 UTC, maggo commented on contracts/XGStudio.cdc
> +                        name: brand.brandName == "xGrunning" ? "xGMove" : brand.brandName,
Done! Since it's always set we can simplify to `name: brand.data["name"] ?? "",`

2022-09-20 13:49 UTC, maggo commented on contracts/XGStudio.cdc
> +                        externalURL: MetadataViews.ExternalURL(brand.data["websiteUrl"] ?? "https://xgrunning.io"), // @TODO: Update fallback
Done!

2022-09-20 14:00 UTC, maggo commented
* Added thumbnail mapping
* Updated brand data keys and socials
* Updated fallback URL

## Todo
* Dynamic editions
* Royalties
* Dynamic Social links, dynamic brand data

2022-09-20 15:23 UTC, maggo commented on contracts/XGStudio.cdc
> +                            // @TODO: Implement dynamic socials list
cadence doesn't have string.split :( We'd need to find another way to configure this. As discussed, updating the data field to be `{String: AnyStruct}` or adding a new field with this type might be an option so we have 
```
socials: {
  twitter: "https://twitter",
  discord: "https://discord"
}
```

2022-09-27 19:28 UTC, yellowBirdy requested changes

2022-09-27 19:28 UTC, yellowBirdy commented on contracts/XGStudio.cdc
> +                    description: "xGStudios Cut"
`                    description: "Artist"
`

2022-09-27 19:28 UTC, yellowBirdy commented on contracts/XGStudio.cdc
> +                            description: "xGFootball Cut"
`                            description: "xGFootball treasury"
`

2022-09-27 19:28 UTC, yellowBirdy commented on contracts/XGStudio.cdc
> +                            description: "xGMove Cut"
`description: "xGMove treasury"
`

2022-09-27 19:28 UTC, yellowBirdy commented on contracts/XGStudio.cdc
> +                // @TODO: Identify xGMove events
`} else if  (tempalte.brandId == 2){`

2022-09-27 19:28 UTC, yellowBirdy commented on contracts/XGStudio.cdc
> +            if (templateData["activityType"] as! String? == "Football") {
} else if (tempalte.brandId == 1){

2022-09-28 14:05 UTC, yellowBirdy approved these changes

2022-09-28 14:06 UTC, merged